ws_method_whitelist = [
  "eth_subscribe",
  "eth_call",
  "eth_chainId"
]
ws_backend_group = "main"

[server]
rpc_host = "0.0.0.0"
rpc_port = 8080
ws_host = "0.0.0.0"
ws_port = 8085
max_body_size_bytes = 10485760
max_concurrent_rpcs = 1000
log_level = "info"

[backend]
response_timeout_seconds = 5
max_response_size_bytes = 5242880
max_retries = 3
out_of_service_seconds = 600
max_latency_threshold = "30s"
max_degraded_latency_threshold = "10s"
max_error_rate_threshold = 0.3

[backends]
[backends.geth]
rpc_url = "http://op-geth:8545"
ws_url = "http://op-geth:8546"
max_rps = 3
max_ws_conns = 1
consensus_receipts_target = "eth_getBlockReceipts"

[backend_groups]
[backend_groups.main]
backends = ["geth"]
consensus_aware = false

[backend_groups.sequencer]
backends = ["geth"]

[rpc_method_mappings]
web3_clientVersion = "main"
web3_sha3 = "main"
net_version = "main"
net_peerCount = "main"
net_listening = "main"
eth_blockNumber = "main"
eth_call = "main"
eth_getBalance = "main"
eth_getStorageAt = "main"
eth_getTransactionCount = "main"
eth_getBlockTransactionCountByHash = "main"
eth_getBlockTransactionCountByNumber = "main"
eth_getUncleCountByBlockHash = "main"
eth_getUncleCountByBlockNumber = "main"
eth_getCode = "main"
eth_sendRawTransaction = "main"
eth_getBlockByHash = "main"
eth_getBlockByNumber = "main"
eth_getTransactionByHash = "main"
eth_getTransactionByBlockHashAndIndex = "main"
eth_getTransactionByBlockNumberAndIndex = "main"
eth_getUncleByBlockHashAndIndex = "main"
eth_getUncleByBlockNumberAndIndex = "main"
eth_newFilter = "main"
eth_newBlockFilter = "main"
eth_newPendingTransactionFilter = "main"
eth_uninstallFilter = "main"
eth_getFilterChanges = "main"
eth_getFilterLogs = "main"
eth_getLogs = "main"
eth_estimateGas = "main"
eth_gasPrice = "main"
eth_protocolVersion = "main"
eth_syncing = "main"
eth_coinbase = "main"
eth_mining = "main"
eth_hashrate = "main"
eth_chainId = "main"
eth_getBlockReceipts = "sequencer"
eth_getTransactionReceipt = "sequencer"