name: Build blockscout docker image

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: planetarium/mothership-l2launcher-blockscout
  BLOCKSCOUT_VERSION: 5.2.2

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5.0.0
        with:
          context: "https://github.com/blockscout/blockscout.git#tags/v${{ env.BLOCKSCOUT_VERSION }}-beta"
          file: docker/Dockerfile
          build-args: RELEASE_VERSION=${{ env.BLOCKSCOUT_VERSION }}
          tags: ${{ env.IMAGE_NAME }}:${{ env.BLOCKSCOUT_VERSION }}
          platforms: linux/amd64,linux/arm64/v8
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
